language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libusb-dev libftdi1-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
